on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Extract Action
      uses: ihiroky/extract-action@v1
      with:
        file_path: './source/velocity_modules.zip'
